mysql:
  config: charset=utf8mb4
  host: 127.0.0.1
  prot: 3306
  db: gvb_db
  user: root
  password: 123456
  log_level: dev
logger:
  level: info
  prefix: "[gvb]"
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  prot: 8080
  env: release
site-info:
  create_at: 2024-8-16
  bei_an: "xxxxxxx"
  title: bramble的个人博客
  qq_image: c:\Users\ccl\Desktop\OIP-C.jpg
  version: 1.0.0
  email: 3478034982@qq.com
  name: bramble
  job: 后端开发
  addr: 河南
  slogan: bramble博客
  web: http://www.bramble.com
  github_url: https://github.com/cclxionger