
CREATE DATABASE IF NOT EXISTS gvb;

USE gvb;


CREATE TABLE IF NOT EXISTS banner_models (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    hash VARCHAR(32) COMMENT 'Hash 值',
    name VARCHAR(100) COMMENT '文件名'
)ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
mapstructure